
POST https://localhost:3322/api/subscription HTTP/1.1
Content-Type: application/json

{
  "Endpoint": "https://localhost:5001/api/consume",
  "Topics": [
    "Avalier.Busk.Contracts.JobCommenced",
    "Avalier.Busk.Contracts.JobCompleted"
  ]
}